default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: zk
  password: zk

development:
  <<: *default
  database: zk_app_development

test:
  <<: *default
  database: zk_app_test

production:
  <<: *default
  database: zk_app_production
  username: zk_app
  password: <%= ENV['ZK_APP_DATABASE_PASSWORD'] %>
